[bash_profile] Improved the llvm cmd to should builds.

diff --git a/dotfiles/conf/bash_profile b/dotfiles/conf/bash_profile
--- a/dotfiles/conf/bash_profile
+++ b/dotfiles/conf/bash_profile
@@ -232,7 +232,7 @@ function llvm {
   echo ">> cd into llvm build folder" && cd ~/Workspace/build/llvm/
   echo ">> git lite prompt mode is enabled" && ed_lite_prompt
   echo -n ">> curret build: " && \
-      (ls -d build* 2> /dev/null || echo "(not found)")
+      (ls -d *build* 2> /dev/null || echo "(not found)")
 }
 
 # ------------------------------------------------------------------------------
